### ISSUE TITLE
Windows 11 is not working?

### ISSUE THREAD

**Issue by Giton22** [crazyklatsch/Arctis7_BatteryReader_rs#2]
I tried to install it on windows 11 but not seem to work. I can't find anything on the tray

**Comment by crazyklatsch** [comment]
Hmm, i'm using it on Windows 11.
I will write some more diagnostic code soon.

**Comment by crazyklatsch** [comment]
@Giton22 
Did you restart your computer? In the current version (1.0.0) of the installer the program is added to autostart, but not to your programs itself (so it cannot be found by searching your programs, only in your "install/deinstall programs settings"). And also it's not started on install.
I'm fixing this with the version 1.1.0 that also brings support for identifying other headsets.
