### ISSUE TITLE
Crashes when charger cable attached [SOLVED]

### ISSUE THREAD

**Issue by thoys** [crazyklatsch/Arctis7_BatteryReader_rs#3]
When the charger cable is attached for my Wireless headset it is at 100%, which makes the program crash.

Reason: only 100 of the 101 Icon's are loaded. 0-100 (100 is exclusive), I'll provide a PR that fixes the load icons function.

BTW, Thanks for providing this tray app, always got annoyed how the normal charge indicator is hidden behind some config in a GUI app.

**Comment by crazyklatsch** [comment]
Hey,
Thank you very much for pointing this out :D
I already saw it crashing a couple of times but didn't have the time to investigate.
It seems a rookie mistake has slipped in when I was writing this XD
Will review and merge tomorrow!

**Comment by thoys** [comment]
No worries, I couldn't initially get this to run so I got to the bottom of it, it didn't seem like a obvious mistake. We Ain't LUA Programmers are WE? (Where all the indexes start at 1 by default!!!)
